### ISSUE TITLE
Chapter 3: dir_creator.cpp code block missing braces

### ISSUE THREAD

**Issue by jeffbi** [PacktPublishing/C-Programming-for-Linux-Systems#1]
The `dir_creator.cpp` file in Chapter 3 is missing braces on the `else` clause. Despite the indentation, the code will display the contents of the `ec` variable regardless of whether the call to `create_directory` fails.

The `else` clause should be:
```
else {
    cout << "Directory creation failed!\n";
    cout << ec.category().name() << endl;
}
```

**Comment by dandree2** [comment]
Thanks - I fixed this!
