### ISSUE TITLE
Chapter 9: smart_pointers.cpp initializes shared_ptr object with make_unique

### ISSUE THREAD

**Issue by jeffbi** [PacktPublishing/C-Programming-for-Linux-Systems#3]
Lines 24 and 25 of `smart_pointers.cpp` initializes a `shared_ptr` object using `make_unique` rather than `make_shared`. Since `shared_ptr` has a constructor that takes a `unique_ptr`, the code compiles and runs, but is a bit less efficient than using the result of `make_shared`, and the intent is less clear.

The code
```
    shared_ptr<Book> book2 = 
        make_unique<Book>("Dune");
```
should be
```
    shared_ptr<Book> book2 = 
        make_shared<Book>("Dune");
```

**Comment by dandree2** [comment]
Thanks for catching this - I'm fixing it!
